SELECT * FROM customer;
----------------------------------------------------------------------------------------------------------
---Business Insights Questions
----------------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------------
---1.Which category generates highest revenue?
SELECT category,
	ROUND(SUM(purchase_amount::NUMERIC),2) AS highest_revenue
	FROM customer
	GROUP BY category
	ORDER BY highest_revenue DESC;

		-- Business Problem: 
				--We do not know which category gives the most revenue.
		-- Impact:
				-- Helps identify top revenue categories
				-- Supports better inventory and stock decisions
				-- Improves focus in marketing and sales strategy
---------------------------------------------------------------------------------------------------------	
---2.Are discounts actually increasing purchase value?
SELECT discount_applied,
	ROUND(SUM(purchase_amount::NUMERIC),2) AS highest_revenue,
	ROUND(AVG(purchase_amount::NUMERIC),2) AS average_purchase
	FROM customer
	GROUP BY discount_applied;

		-- Business Problem:
				--We do not know if discounts are helping or reducing profit.
		-- Impact:
				-- Helps measure real impact of discounts on sales
				-- Avoids unnecessary discount usage
				-- Improves overall profit margin
---------------------------------------------------------------------------------------------------------
---3.What is the total revenue generated by male and female customer? 
SELECT gender, 
	ROUND(SUM(purchase_amount::NUMERIC),2) AS highest_revenue
	FROM customer
	GROUP BY gender
	ORDER BY highest_revenue DESC;

		-- Business Problem:
				--We do not know which gender spends more.
		-- Impact:
				-- Helps understand customer buying patterns
				-- Supports targeted marketing campaigns
				-- Improves personalization of offers
----------------------------------------------------------------------------------------------------------
---4.Which customer used a discount but still spent more then the average purchase amount ?
SELECT 
	customer_id,
	purchase_amount,
	discount_applied
	FROM customer
	WHERE discount_applied = 'Yes' AND purchase_amount > (SELECT AVG(purchase_amount) FROM customer)
	LIMIT 10;

			-- Business Problem: 
					--We cannot find customers who use discounts but still spend more.
		-- Impact:
					-- Helps identify high-value customers
					-- Enables smarter discount targeting
					-- Increases customer retention and revenue
----------------------------------------------------------------------------------------------------------	
---5.Which are the top/bottom 5 products with the highest average review rating.
--Top 5
SELECT 
	item_purchased,
	ROUND(AVG(review_rating::NUMERIC),2) AS avg_rating
	FROM customer
	GROUP BY item_purchased
	ORDER BY AVG(review_rating) DESC
	limit 5;
--Bottom 5
SELECT 
	item_purchased,
	ROUND(AVG(review_rating::NUMERIC),2) AS avg_rating
	FROM customer
	GROUP BY item_purchased
	ORDER BY AVG(review_rating) ASC
	limit 5;
		-- Business Problem: 
				--We do not know which products customers like or dislike.
		-- Impact:
				-- Helps identify top and low performing products
				-- Supports product improvement decisions
				-- Enhances overall customer satisfaction					
----------------------------------------------------------------------------------------------------------
---6.Average purchase: Standard vs Express shipping
SELECT 
	shipping_type,
	COUNT(DISTINCT customer_id) AS order_placed,
	ROUND(AVG(purchase_amount::NUMERIC),2) AS avg_purchase,
	ROUND(SUM(purchase_amount::NUMERIC),2) AS revenue
	FROM customer
	GROUP BY shipping_type
	ORDER BY revenue DESC;

		-- Business Problem: 
				--We do not know if fast shipping increases spending.
		-- Impact:
				-- Helps evaluate impact of shipping options on sales
				-- Supports better pricing for delivery services
				-- Encourages higher order value through faster delivery
----------------------------------------------------------------------------------------------------------
---7.Do subscribed customers spend more ? Compare average speed and total revenue between
---subscribers and non-subscribers.
SELECT
	subscription_status,
	COUNT(customer_id) AS users,
	ROUND(AVG(purchase_amount::NUMERIC),2) AS avg_revnue,
	ROUND(SUM(purchase_amount::NUMERIC),2) AS total_revenue
	FROM customer
	GROUP BY subscription_status
	ORDER BY total_revenue DESC;
		-- Business Problem:
				--We do not know if subscription customers spend more.
		-- Impact:
				-- Helps evaluate success of subscription model
				-- Supports improvement in loyalty programs
				-- Increases long-term customer value
----------------------------------------------------------------------------------------------------------
---8.Top 5 products with highest discount usage %
SELECT 
	item_purchased,
	COUNT(item_purchased) AS total_number_of_times_sold,
	COUNT(CASE WHEN discount_applied = 'Yes' THEN 1 END) AS number_of_times_sold_when_discount_applied,
	COUNT(CASE WHEN discount_applied = 'Yes' THEN 1 END) * 100.0/COUNT(*) AS discount_percent
	FROM customer
	GROUP BY item_purchased
	ORDER BY discount_percent DESC
	LIMIT 5;

			-- Business Problem:
					--Some products depend too much on discounts.
			-- Impact:
					-- Helps identify products driven by discounts
					-- Supports better pricing strategies
					-- Reduces loss in profit margins
----------------------------------------------------------------------------------------------------------
---9.Segment customer into new, returning and loyal based on their total number of previous purchase,
--and show the count of each segment.
SELECT
	CASE
		WHEN previous_purchases = '0' THEN 'New Customer'
		WHEN previous_purchases BETWEEN 1 AND 15 THEN 'Returning Customer'
	ELSE 'Loyal Customers'
	END AS customer_segment, 
	COUNT(*) AS customer_count
	FROM customer
	GROUP BY
	CASE
		WHEN previous_purchases = '0' THEN 'New Customer'
		WHEN previous_purchases BETWEEN 1 AND 15 THEN 'Returning Customer'
	ELSE 'Loyal Customers'
	END;

		-- Business Problem: 
				--We are not grouping customers properly.
		-- Impact:
				-- Enables clear customer segmentation
				-- Supports personalized marketing strategies
				-- Improves customer retention and engagement
----------------------------------------------------------------------------------------------------------
---10.What are the top 3 most purchased products within each category ?
WITH CTE AS
(
SELECT 
	category, 
	item_purchased,
	COUNT(item_purchased) AS most_purchased,
	RANK() OVER (PARTITION BY category ORDER BY COUNT(item_purchased) DESC) AS RNK
	FROM customer
	GROUP BY category, item_purchased
	)
SELECT * FROM CTE
WHERE RNK <= 3;

		-- Business Problem:
				--We do not know top products in each category.
		-- Impact:
				-- Helps identify best-selling products
				-- Supports better product placement
				-- Increases sales through focused promotions
----------------------------------------------------------------------------------------------------------
---11.Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe ?
SELECT 
	CASE 
	WHEN previous_purchases > 5 THEN 'Repeat Buyers'
	ELSE 'Normal Buyers'
END AS customer_type,
subscription_status,
COUNT(*) AS customer_count,
COUNT(*) * 100.0 / SUM(COUNT(*)) OVER (PARTITION BY CASE
	WHEN previous_purchases > 5 THEN 'Repeat Buyers'
	ELSE 'Normal Buyers'
	END
	) AS percents
FROM customer
GROUP BY CASE
	WHEN previous_purchases > 5 THEN 'Repeat Buyers'
	ELSE 'Normal Buyers'
	END, subscription_status;

		-- Business Problem: 
				--We do not know if loyal customers take subscriptions.
		-- Impact:
				-- Helps understand customer loyalty behavior
				-- Supports better subscription targeting
				-- Improves conversion to paid programs
----------------------------------------------------------------------------------------------------------
---12.What is the revenue contribution of each age group ?
SELECT 
	CASE
		WHEN age BETWEEN 18 AND 25 THEN '18-25'
		WHEN age BETWEEN 26 AND 35 THEN '26-35'
		WHEN age BETWEEN 36 AND 50 THEN '36-50'
		ELSE '51+'
	END AS age_group,
	ROUND(SUM(purchase_amount::NUMERIC),2) AS total_revenue
FROM customer
GROUP BY CASE
		WHEN age BETWEEN 18 AND 25 THEN '18-25'
		WHEN age BETWEEN 26 AND 35 THEN '26-35'
		WHEN age BETWEEN 36 AND 50 THEN '36-50'
		ELSE '51+'
	END
	ORDER BY total_revenue DESC;

		-- Business Problem:
				--We do not know which age group spends more.
		-- Impact:
				-- Helps identify high-value age groups
				-- Supports targeted marketing by age
				-- Improves campaign effectiveness
----------------------------------------------------------------------------------------------------------

